version: "3"
services:
  sky-testing: #change services name here
    container_name: sky-testing #change container name here
    image: sky-testing #change image name here
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/home/node/backend
    stdin_open: true
    tty: true
    environment:
      HOST: 0.0.0.0
    networks:
      - skytesting_localnet #change networks name here
networks:
  skytesting_localnet: #change networks name here
    external: true
