version: "3"
services:
  base-backend: #change services name here
    container_name: base-backend #change container name here
    image: base-backend #change image name here
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/home/node/backend
    stdin_open: true
    tty: true
    environment:
      HOST: 0.0.0.0
    networks:
      - skybase_localnet #change networks name here
networks:
  skybase_localnet: #change networks name here
    external: true
