version: "3"
services:
  mysql: #change services name here
    container_name: mysql #change container name here
    image: "mysql:8.0.33"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456" # change root password here
      MYSQL_DATABASE: "rocket_base" # change default schema here
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - localnet #change networks name here
networks:
  localnet: #change networks name here
    name: skybase_localnet #change networks name here
    driver: bridge
