version: "3"
services:
  redis: #change services name here
    container_name: redis #change container name here
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    # command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure:3
    networks:
      - skybase_localnet #change networks name here

networks:
  skybase_localnet:
    external: true
